version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - tr-net
    volumes:
      - home_js:/serv/app
    ports:
      - 80:80
      - 3000:3000

volumes:
  home_js:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/ft_transcendence/packages/backend/app

networks:
    tr-net:
      name: tr-net
      # driver: bridge
      # ipam:
      #   config:
      #    - subnet: 172.16.0.0/28
