version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - tr-net
    volumes:
        - ./packages/backend/db:/var/lib/postgresql
        # - ./packages:/serv
        # - bk:/srv/app
    tty: true
    ports:
      - 4242:4242
      - 5001:5000
    depends_on:
      - database
  
  database:
    container_name: database
    image: postgres:15-alpine3.17
    ports:
      - 5432:5432
    tty: true
    env_file:
      - .env
    networks:
      - tr-net
  frontend:
    container_name: frontend
    build:
      context: ./packages/front_end
      dockerfile: Dockerfile
    restart: always
    networks:
      - tr-net
    volumes:
      - "./packages/front_end/src:/app/src"
    ports:
      - 3000:3000


networks:
    tr-net:
      name: tr-net
      # driver: bridge
      # ipam:
      #   config:
      #    - subnet: 172.16.0.0/28

# volumes:
#   bk:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${HOME}/ft_transcendence/packages/backend