version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./packages
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./packages/.env
    networks:
      - tr-net
    volumes:
        - application:/application/
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - database
  
  database:
    container_name: database
    image: postgres:15-alpine3.17
    ports:
      - 5432:5432
    tty: true
    env_file:
      - .env
    networks:
      - tr-net

networks:
    tr-net:
      name: tr-net

volumes:
  application: