version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - tr-net
    volumes:
        - ./packages/backend:/serv/backend
        # - ./packages:/serv
        # - bk:/srv/app
    tty: true
    ports:
      - 4242:4242
      - 5001:5000
    depends_on:
      - database
  
  database:
    container_name: database
    image: postgres:15-alpine3.17
    ports:
      - 5432:5432
    tty: true
    env_file:
      - .env
    networks:
      - tr-net

  frontend:
    container_name: frontend
    build:
      context: ./packages/front_end
      dockerfile: Dockerfile
    # restart: always to be re-enabled later
    networks:
      - tr-net
    environment:
      - REACT_APP_HOST=localhost
      - REACT_APP_BACKEND_PORT=8080
    volumes:
      - ./packages/front_end/src:/app/src/
    ports:
      - 3000:3000

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./packages/.env
    ports:
      - "8080:80"
    networks:
      - tr-net
    depends_on:
      - frontend

networks:
    tr-net:
      name: tr-net
      # driver: bridge
      # ipam:
      #   config:
      #    - subnet: 172.16.0.0/28

volumes:
  backend:
  frontend:
# volumes:
#   bk:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${HOME}/ft_transcendence/packages/backend