version: '3.9'

services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: ./packages/backend
  #     dockerfile: Dockerfile
  #   restart: always
  #   networks:
  #     - tr-net
  #   volumes:
  #     - home_back:/serv/app
  #   ports:
  #     - 4242:4242

  frontend:
    container_name: frontend
    build:
      context: ./packages/front_end
      dockerfile: Dockerfile
    restart: always
    networks:
      - tr-net
    volumes:
      - home_front:/app
    ports:
      - 3000:3000
    command: "yarn start"

volumes:
  home_back:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/ft_transcendence/packages/backend/app
  home_front:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/ft_transcendence/packages/front_end

networks:
    tr-net:
      name: tr-net
      # driver: bridge
      # ipam:
      #   config:
      #    - subnet: 172.16.0.0/28
